name: droobi
description: Droobi - Wearable navigation app for visually impaired users.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.32.12
  flutter_riverpod: ^2.5.1

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  http: ^1.2.1

  whisper_flutter_new:

  record:

  path_provider:

  shared_preferences: ^2.5.3

  flutter_tts: ^4.0.2
  geolocator: ^12.0.0
  flutter_compass: ^0.8.1
  cupertino_icons: ^1.0.6
  crypto: ^3.0.7
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_bg.png
    - assets/images/app_logo.png
    - assets/images/Favorites_bg.png
    - assets/images/uni_bg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21