// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4VFyGVYM1gpVF6it-a3N28Pj296uDeQ',
    appId: '1:286313133920:web:5bdcd22e1fb314ef435005',
    messagingSenderId: '286313133920',
    projectId: 'droobi-daeb8',
    authDomain: 'droobi-daeb8.firebaseapp.com',
    storageBucket: 'droobi-daeb8.firebasestorage.app',
    measurementId: 'G-7QMP0QDTPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZBwspbhwv_yZNDn7Q5eSnMD6tP1OeJEk',
    appId: '1:286313133920:android:e7c3935218d88ff1435005',
    messagingSenderId: '286313133920',
    projectId: 'droobi-daeb8',
    storageBucket: 'droobi-daeb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLm-1-mnOL0NZ1fWLPBTasTgK11edkxbQ',
    appId: '1:286313133920:ios:6768789fcc6c2fb1435005',
    messagingSenderId: '286313133920',
    projectId: 'droobi-daeb8',
    storageBucket: 'droobi-daeb8.firebasestorage.app',
    iosBundleId: 'com.example.droobi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLm-1-mnOL0NZ1fWLPBTasTgK11edkxbQ',
    appId: '1:286313133920:ios:6768789fcc6c2fb1435005',
    messagingSenderId: '286313133920',
    projectId: 'droobi-daeb8',
    storageBucket: 'droobi-daeb8.firebasestorage.app',
    iosBundleId: 'com.example.droobi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz4VFyGVYM1gpVF6it-a3N28Pj296uDeQ',
    appId: '1:286313133920:web:6c38fd39a867513c435005',
    messagingSenderId: '286313133920',
    projectId: 'droobi-daeb8',
    authDomain: 'droobi-daeb8.firebaseapp.com',
    storageBucket: 'droobi-daeb8.firebasestorage.app',
    measurementId: 'G-72BPXWL42S',
  );
}
